name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 1.0.1-beta
api: 4.0.0
author: brokiem

mcpe-protocol: [407, 408, 418, 419, 421, 422, 428]

website: https://github.com/brokiem/SimpleNPC

permissions:
  snpc.spawn:
    default: op
  snpc.edit:
    default: op
  snpc.remove:
    default: op
  snpc.migrate:
    default: op
  snpc.list:
    default: op
  snpc.rca:
    default: op
